import imageCard1 from './card/1.webp'
import imageCard2 from './card/2.webp'
import imageCard3 from './card/3.webp'
import imageCard4 from './card/4.webp'
import imageCard5 from './card/5.webp'
import imageCard6 from './card/6.webp'

export const events = [
  {
    id: 1,
    image: imageCard1,
    date: '2022-11-05',
    title: '100 Cities Project: Fighting Loneliness | Dinner with...',
    time: 'Saturday • 8:00 PM + 42 more',
    location: 'Cairo',
    category: 'Food & Drink',
    price: '$23.18',
    followers: 174,
    hostedBy: 'Jane Doe',
    highlight :"Sponsored",
  },
  {
    id: 2,
    image: imageCard2,
    date: '2022-10-14',
    title: 'Global Networking Night | Meet & Connect',
    time: 'Friday • 7:00 PM',
    location: 'Dubai',
    category: 'Business',
    price: '$30.50',
    followers: 120,
    hostedBy: 'Bob Johnson',
    highlight :"decrease 20%",
  },
  {
    id: 3,
    image: imageCard3,
    date: '2024-05-20',
    title: 'Tech Conference 2024 | Learn & Grow',
    time: 'Monday • 10:00 AM',
    location: 'New York',
    category: 'Tech',
    price: '$50.00',
    followers: 250,
    hostedBy: 'Alice Smith',
    highlight :"decrease 20%",
  },
  {
    id: 4,
    image: imageCard4,
    date: '2022-09-30',
    title: 'Food Lovers Meetup | Taste & Enjoy',
    time: 'Sunday • 6:00 PM',
    location: 'Paris',
    category: 'Food Lovers',
    price: '$18.99',
    followers: 95,
    hostedBy: 'John Doe',
    highlight :"decrease 20%",
  },
  {
    id: 5,
    image: imageCard5,
    date: '2022-12-15',
    title: 'Winter Music Festival | Live Performances',
    time: 'Thursday • 9:00 PM',
    location: 'Berlin',
    category: 'Music',
    price: '$45.00',
    followers: 320,
    hostedBy: 'Michael Brown',
    highlight :"Sponsored",
  },
  {
    id: 6,
    image: imageCard6,
    date: '2023-01-10',
    title: 'New Year Business Summit',
    time: 'Tuesday • 11:00 AM',
    location: 'London',
    category: 'Business',
    price: '$75.00',
    followers: 210,
    hostedBy: 'Sarah Johnson',
    highlight :"Sponsored",
  },
  {
    id: 7,
    image: imageCard1,
    date: '2024-07-22',
    title: 'AI & Machine Learning Workshop',
    time: 'Monday • 2:00 PM',
    location: 'San Francisco',
    category: 'Tech',
    price: '$60.00',
    followers: 275,
    hostedBy: 'Elon Wright',
    highlight :"Sponsored",
  },
  {
    id: 8,
    image: imageCard2,
    date: '2024-08-15',
    title: 'Summer Art Exhibition',
    time: 'Thursday • 5:00 PM',
    location: 'Rome',
    category: 'Art & Culture',
    price: '$20.00',
    followers: 180,
    hostedBy: 'Sophia Martinez',
    highlight :"Sponsored",
  },
  {
    id: 9,
    image: imageCard3,
    date: '2023-03-08',
    title: 'Women in Business Conference',
    time: 'Wednesday • 10:00 AM',
    location: 'Toronto',
    category: 'Business',
    price: '$55.00',
    followers: 230,
    hostedBy: 'Emma Watson',
    highlight :"Sponsored",
  },
  {
    id: 10,
    image: imageCard4,
    date: '2024-09-30',
    title: 'Startup Pitch Night',
    time: 'Friday • 7:30 PM',
    location: 'Tokyo',
    category: 'Entrepreneurship',
    price: 'Free',
    followers: 300,
    hostedBy: 'Hiro Tanaka',
    highlight :"Sponsored",
  },
  {
    id: 11,
    image: imageCard5,
    date: '2023-11-11',
    title: 'Gaming Convention 2023',
    time: 'Saturday • 11:00 AM',
    location: 'Los Angeles',
    category: 'Gaming',
    price: '$35.00',
    followers: 500,
    hostedBy: 'David Lee',
    highlight :"Sponsored",
  },
  {
    id: 12,
    image: imageCard6,
    date: '2024-12-20',
    title: 'Christmas Charity Gala',
    time: 'Wednesday • 8:00 PM',
    location: 'Sydney',
    category: 'Charity',
    price: '$80.00',
    followers: 150,
    hostedBy: 'Grace Taylor',
    highlight :"Sponsored",
  },
  
];

